# Generated by Django 5.1.15 on 2026-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(default='Контакти', max_length=200, verbose_name='Заголовок (UA)')),
                ('title_it', models.CharField(default='Contatti', max_length=200, verbose_name='Заголовок (IT)')),
                ('intro_uk', models.TextField(blank=True, default='', verbose_name='Вступ (UA)')),
                ('intro_it', models.TextField(blank=True, default='', verbose_name='Вступ (IT)')),
                ('working_hours_uk', models.TextField(blank=True, default='', verbose_name='Графік (UA)')),
                ('working_hours_it', models.TextField(blank=True, default='', verbose_name='Графік (IT)')),
            ],
            options={
                'verbose_name': 'Сторінка «Контакти»',
                'verbose_name_plural': 'Сторінка «Контакти»',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_uk', models.CharField(max_length=120, verbose_name='Місто (UA)')),
                ('city_it', models.CharField(blank=True, default='', max_length=120, verbose_name='Місто (IT)')),
                ('address_uk', models.CharField(max_length=255, verbose_name='Адреса (UA)')),
                ('address_it', models.CharField(blank=True, default='', max_length=255, verbose_name='Адреса (IT)')),
                ('map_url', models.URLField(blank=True, default='', verbose_name='Посилання на карту')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='offices/', verbose_name='Фото кабінету')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінети',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20, verbose_name='Платформа')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Соц. посилання',
                'verbose_name_plural': 'Соц. посилання',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('platform',), name='unique_social_platform')],
            },
        ),
    ]
