# Generated by Django 5.1.15 on 2026-05-14 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_update_contacts_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('read', 'Прочитано'), ('replied', 'Відповіли')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запит на консультацію',
                'verbose_name_plural': 'Запити на консультацію',
                'ordering': ['-created_at'],
            },
        ),
    ]
