# Generated by Django 5.1.15 on 2026-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name_uk', models.CharField(default='', max_length=120, verbose_name='Назва бренду (UA)')),
                ('brand_name_it', models.CharField(default='', max_length=120, verbose_name='Назва бренду (IT)')),
                ('tagline_uk', models.CharField(blank=True, default='', max_length=240, verbose_name='Підзаголовок (UA)')),
                ('tagline_it', models.CharField(blank=True, default='', max_length=240, verbose_name='Підзаголовок (IT)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='OG-зображення')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
