from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UILabels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nav_skip_uk", models.CharField(default="Перейти до контенту", max_length=80, verbose_name="Пропустити до контенту (UA)")),
                ("nav_skip_it", models.CharField(default="Vai al contenuto", max_length=80, verbose_name="Пропустити до контенту (IT)")),
                ("nav_toggle_uk", models.CharField(default="Відкрити меню", max_length=60, verbose_name="Відкрити меню (UA)")),
                ("nav_toggle_it", models.CharField(default="Apri menu", max_length=60, verbose_name="Відкрити меню (IT)")),
                ("nav_home_uk", models.CharField(default="Головна", max_length=60, verbose_name="Пункт «Головна» (UA)")),
                ("nav_home_it", models.CharField(default="Home", max_length=60, verbose_name="Пункт «Головна» (IT)")),
                ("nav_about_uk", models.CharField(default="Про мене", max_length=60, verbose_name="Пункт «Про мене» (UA)")),
                ("nav_about_it", models.CharField(default="Su di me", max_length=60, verbose_name="Пункт «Про мене» (IT)")),
                ("nav_services_uk", models.CharField(default="З чим я працюю", max_length=80, verbose_name="Пункт «З чим я працюю» (UA)")),
                ("nav_services_it", models.CharField(default="Con cosa lavoro", max_length=80, verbose_name="Пункт «З чим я працюю» (IT)")),
                ("nav_therapy_uk", models.CharField(default="Як проходять зустрічі", max_length=80, verbose_name="Пункт «Зустрічі» (UA)")),
                ("nav_therapy_it", models.CharField(default="Gli incontri", max_length=80, verbose_name="Пункт «Зустрічі» (IT)")),
                ("nav_contacts_uk", models.CharField(default="Контакти", max_length=60, verbose_name="Пункт «Контакти» (UA)")),
                ("nav_contacts_it", models.CharField(default="Contatti", max_length=60, verbose_name="Пункт «Контакти» (IT)")),
                ("footer_format_uk", models.CharField(default="Онлайн і офлайн", max_length=80, verbose_name="Футер: формат (UA)")),
                ("footer_format_it", models.CharField(default="Online & di persona", max_length=80, verbose_name="Футер: формат (IT)")),
                ("footer_intro_uk", models.CharField(default="Перша розмова", max_length=80, verbose_name="Футер: перша розмова (UA)")),
                ("footer_intro_it", models.CharField(default="Conversazione di prova", max_length=80, verbose_name="Футер: перша розмова (IT)")),
                ("hero_meta_uk", models.CharField(default="Онлайн та вживу (Мілан, Комо)", max_length=120, verbose_name="Hero: рядок формату (UA)")),
                ("hero_meta_it", models.CharField(default="Online e di persona (Milano, Como)", max_length=120, verbose_name="Hero: рядок формату (IT)")),
                ("hero_badge_uk", models.CharField(default="Є вільні слоти", max_length=60, verbose_name="Hero: бейдж слотів (UA)")),
                ("hero_badge_it", models.CharField(default="Posti disponibili", max_length=60, verbose_name="Hero: бейдж слотів (IT)")),
                ("hero_about_link_uk", models.CharField(default="Про мене", max_length=60, verbose_name="Hero: посилання «Про мене» (UA)")),
                ("hero_about_link_it", models.CharField(default="Su di me", max_length=60, verbose_name="Hero: посилання «Про мене» (IT)")),
                ("about_tag_uk", models.CharField(default="Про мене", max_length=60, verbose_name="Про мене: тег секції (UA)")),
                ("about_tag_it", models.CharField(default="Su di me", max_length=60, verbose_name="Про мене: тег секції (IT)")),
                ("about_eyebrow_uk", models.CharField(default="Знайомство", max_length=80, verbose_name="Про мене: eyebrow (UA)")),
                ("about_eyebrow_it", models.CharField(default="Conosciamoci", max_length=80, verbose_name="Про мене: eyebrow (IT)")),
                ("about_read_more_uk", models.CharField(default="Читати далі –", max_length=60, verbose_name="Про мене: посилання «Читати далі» (UA)")),
                ("about_read_more_it", models.CharField(default="Leggi di più", max_length=60, verbose_name="Про мене: посилання «Читати далі» (IT)")),
                ("about_contact_link_uk", models.CharField(default="Написати мені", max_length=60, verbose_name="Про мене: посилання «Написати» (UA)")),
                ("about_contact_link_it", models.CharField(default="Scrivimi", max_length=60, verbose_name="Про мене: посилання «Написати» (IT)")),
                ("about_edu_num_uk", models.CharField(default="01 — Освіта", max_length=40, verbose_name="Картка «Освіта»: номер (UA)")),
                ("about_edu_num_it", models.CharField(default="01 — Background", max_length=40, verbose_name="Картка «Освіта»: номер (IT)")),
                ("about_edu_title_uk", models.CharField(default="Освіта", max_length=60, verbose_name="Картка «Освіта»: назва (UA)")),
                ("about_edu_title_it", models.CharField(default="Formazione", max_length=60, verbose_name="Картка «Освіта»: назва (IT)")),
                ("about_approach_num_uk", models.CharField(default="02 — Метод", max_length=40, verbose_name="Картка «Підхід»: номер (UA)")),
                ("about_approach_num_it", models.CharField(default="02 — Metodo", max_length=40, verbose_name="Картка «Підхід»: номер (IT)")),
                ("about_approach_title_uk", models.CharField(default="Підхід", max_length=60, verbose_name="Картка «Підхід»: назва (UA)")),
                ("about_approach_title_it", models.CharField(default="Approccio", max_length=60, verbose_name="Картка «Підхід»: назва (IT)")),
                ("services_eyebrow_uk", models.CharField(default="З чим я працюю", max_length=80, verbose_name="З чим я працюю: eyebrow (UA)")),
                ("services_eyebrow_it", models.CharField(default="Con cosa lavoro", max_length=80, verbose_name="З чим я працюю: eyebrow (IT)")),
                ("services_empty_uk", models.CharField(default="Розділ у підготовці.", max_length=120, verbose_name="З чим я працюю: порожній стан (UA)")),
                ("services_empty_it", models.CharField(default="Sezione in preparazione.", max_length=120, verbose_name="З чим я працюю: порожній стан (IT)")),
                ("services_cta_uk", models.CharField(default="Записатися на консультацію", max_length=80, verbose_name="З чим я працюю: кнопка CTA (UA)")),
                ("services_cta_it", models.CharField(default="Prenota una consulenza", max_length=80, verbose_name="З чим я працюю: кнопка CTA (IT)")),
                ("therapy_eyebrow_uk", models.CharField(default="Як проходить робота", max_length=80, verbose_name="Зустрічі: eyebrow (UA)")),
                ("therapy_eyebrow_it", models.CharField(default="Come lavoriamo", max_length=80, verbose_name="Зустрічі: eyebrow (IT)")),
                ("therapy_steps_eyebrow_uk", models.CharField(default="Шлях", max_length=60, verbose_name="Зустрічі: eyebrow кроків (UA)")),
                ("therapy_steps_eyebrow_it", models.CharField(default="Il percorso", max_length=60, verbose_name="Зустрічі: eyebrow кроків (IT)")),
                ("therapy_steps_title_uk", models.CharField(default="Як ми будемо працювати", max_length=80, verbose_name="Зустрічі: заголовок кроків (UA)")),
                ("therapy_steps_title_it", models.CharField(default="Come si svolge", max_length=80, verbose_name="Зустрічі: заголовок кроків (IT)")),
                ("therapy_pricing_eyebrow_uk", models.CharField(default="Практика", max_length=60, verbose_name="Зустрічі: eyebrow вартості (UA)")),
                ("therapy_pricing_eyebrow_it", models.CharField(default="Pratica", max_length=60, verbose_name="Зустрічі: eyebrow вартості (IT)")),
                ("therapy_pricing_title_uk", models.CharField(default="Тривалість і вартість", max_length=80, verbose_name="Зустрічі: заголовок вартості (UA)")),
                ("therapy_pricing_title_it", models.CharField(default="Durata e tariffe", max_length=80, verbose_name="Зустрічі: заголовок вартості (IT)")),
                ("therapy_pricing_subtitle_uk", models.CharField(default="Одна сесія", max_length=60, verbose_name="Зустрічі: підзаголовок вартості (UA)")),
                ("therapy_pricing_subtitle_it", models.CharField(default="Sessione singola", max_length=60, verbose_name="Зустрічі: підзаголовок вартості (IT)")),
                ("therapy_cta_uk", models.CharField(default="Записатися", max_length=60, verbose_name="Зустрічі: кнопка CTA (UA)")),
                ("therapy_cta_it", models.CharField(default="Prenota", max_length=60, verbose_name="Зустрічі: кнопка CTA (IT)")),
                ("contacts_eyebrow_uk", models.CharField(default="Контакти", max_length=60, verbose_name="Контакти: eyebrow (UA)")),
                ("contacts_eyebrow_it", models.CharField(default="Contatti", max_length=60, verbose_name="Контакти: eyebrow (IT)")),
                ("contacts_phone_uk", models.CharField(default="Телефон", max_length=40, verbose_name="Контакти: підпис телефону (UA)")),
                ("contacts_phone_it", models.CharField(default="Telefono", max_length=40, verbose_name="Контакти: підпис телефону (IT)")),
                ("contacts_hours_uk", models.CharField(default="Графік", max_length=40, verbose_name="Контакти: підпис графіку (UA)")),
                ("contacts_hours_it", models.CharField(default="Orari", max_length=40, verbose_name="Контакти: підпис графіку (IT)")),
                ("contacts_offices_eyebrow_uk", models.CharField(default="Адреси", max_length=60, verbose_name="Контакти: eyebrow кабінетів (UA)")),
                ("contacts_offices_eyebrow_it", models.CharField(default="Indirizzi", max_length=60, verbose_name="Контакти: eyebrow кабінетів (IT)")),
                ("contacts_offices_title_uk", models.CharField(default="Кабінети", max_length=60, verbose_name="Контакти: назва секції кабінетів (UA)")),
                ("contacts_offices_title_it", models.CharField(default="I miei studi", max_length=60, verbose_name="Контакти: назва секції кабінетів (IT)")),
                ("contacts_map_link_uk", models.CharField(default="Відкрити на карті", max_length=60, verbose_name="Контакти: посилання на карту (UA)")),
                ("contacts_map_link_it", models.CharField(default="Apri sulla mappa", max_length=60, verbose_name="Контакти: посилання на карту (IT)")),
                ("form_name_uk", models.CharField(default="Ім'я", max_length=40, verbose_name="Форма: поле «Ім'я» (UA)")),
                ("form_name_it", models.CharField(default="Nome", max_length=40, verbose_name="Форма: поле «Ім'я» (IT)")),
                ("form_message_uk", models.CharField(default="Повідомлення", max_length=60, verbose_name="Форма: поле «Повідомлення» (UA)")),
                ("form_message_it", models.CharField(default="Messaggio", max_length=60, verbose_name="Форма: поле «Повідомлення» (IT)")),
                ("form_submit_uk", models.CharField(default="Надіслати", max_length=40, verbose_name="Форма: кнопка «Надіслати» (UA)")),
                ("form_submit_it", models.CharField(default="Invia", max_length=40, verbose_name="Форма: кнопка «Надіслати» (IT)")),
                ("form_success_uk", models.CharField(default="Дякую! Я відповім вам найближчим часом.", max_length=200, verbose_name="Форма: повідомлення про успіх (UA)")),
                ("form_success_it", models.CharField(default="Grazie! Ti risponderò al più presto.", max_length=200, verbose_name="Форма: повідомлення про успіх (IT)")),
            ],
            options={
                "verbose_name": "Написи інтерфейсу",
                "verbose_name_plural": "Написи інтерфейсу",
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("core", "UILabels").objects.get_or_create(pk=1),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
