# Generated by Django 5.1.15 on 2026-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uilabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='uilabels',
            name='contacts_email_it',
            field=models.CharField(default='Email', max_length=40, verbose_name='Контакти: підпис Email (IT)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='contacts_email_uk',
            field=models.CharField(default='Email', max_length=40, verbose_name='Контакти: підпис Email (UA)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='footer_credit_it',
            field=models.CharField(default='Sviluppato da PrometeyLabs', max_length=80, verbose_name='Футер: підпис розробника (IT)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='footer_credit_uk',
            field=models.CharField(default='Розроблено в PrometeyLabs', max_length=80, verbose_name='Футер: підпис розробника (UA)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='footer_credit_url',
            field=models.CharField(blank=True, default='https://www.prometeylabs.com/', max_length=200, verbose_name='Футер: URL розробника'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='footer_lang_badge',
            field=models.CharField(default='UA · IT', max_length=20, verbose_name='Футер: бейдж мов (UA · IT)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='form_email_it',
            field=models.CharField(default='Email', max_length=40, verbose_name='Форма: поле «Email» (IT)'),
        ),
        migrations.AddField(
            model_name='uilabels',
            name='form_email_uk',
            field=models.CharField(default='Email', max_length=40, verbose_name='Форма: поле «Email» (UA)'),
        ),
    ]
