# Generated by Django 5.1.15 on 2026-04-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(default='Про мене', max_length=200, verbose_name='Заголовок (UA)')),
                ('title_it', models.CharField(default='Su di me', max_length=200, verbose_name='Заголовок (IT)')),
                ('lead_uk', models.TextField(blank=True, default='', verbose_name='Лід (UA)')),
                ('lead_it', models.TextField(blank=True, default='', verbose_name='Лід (IT)')),
                ('body_uk', models.TextField(blank=True, default='', verbose_name='Основний текст (UA)')),
                ('body_it', models.TextField(blank=True, default='', verbose_name='Основний текст (IT)')),
                ('education_uk', models.TextField(blank=True, default='', verbose_name='Освіта (UA)')),
                ('education_it', models.TextField(blank=True, default='', verbose_name='Освіта (IT)')),
                ('approach_uk', models.TextField(blank=True, default='', verbose_name='Підхід (UA)')),
                ('approach_it', models.TextField(blank=True, default='', verbose_name='Підхід (IT)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Про мене',
                'verbose_name_plural': 'Про мене',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_uk', models.CharField(default='', max_length=200, verbose_name='Заголовок героя (UA)')),
                ('hero_title_it', models.CharField(default='', max_length=200, verbose_name='Заголовок героя (IT)')),
                ('hero_subtitle_uk', models.CharField(blank=True, default='', max_length=300, verbose_name='Підзаголовок (UA)')),
                ('hero_subtitle_it', models.CharField(blank=True, default='', max_length=300, verbose_name='Підзаголовок (IT)')),
                ('hero_cta_uk', models.CharField(default='Записатися', max_length=80, verbose_name='Текст кнопки (UA)')),
                ('hero_cta_it', models.CharField(default='Prenota', max_length=80, verbose_name='Текст кнопки (IT)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фото героя')),
                ('positioning_uk', models.TextField(blank=True, default='', verbose_name='Позиціонування (UA)')),
                ('positioning_it', models.TextField(blank=True, default='', verbose_name='Позиціонування (IT)')),
                ('about_teaser_uk', models.TextField(blank=True, default='', verbose_name='Тизер «Про мене» (UA)')),
                ('about_teaser_it', models.TextField(blank=True, default='', verbose_name='Тизер «Про мене» (IT)')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фото для тизера «Про мене»')),
                ('services_intro_uk', models.TextField(blank=True, default='', verbose_name='Тизер «З чим працюю» (UA)')),
                ('services_intro_it', models.TextField(blank=True, default='', verbose_name='Тизер «З чим працюю» (IT)')),
                ('therapy_intro_uk', models.TextField(blank=True, default='', verbose_name='Тизер «Як проходить терапія» (UA)')),
                ('therapy_intro_it', models.TextField(blank=True, default='', verbose_name='Тизер «Як проходить терапія» (IT)')),
                ('contacts_teaser_uk', models.TextField(blank=True, default='', verbose_name='Тизер «Контакти» (UA)')),
                ('contacts_teaser_it', models.TextField(blank=True, default='', verbose_name='Тизер «Контакти» (IT)')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(default='З чим я працюю', max_length=200, verbose_name='Заголовок (UA)')),
                ('title_it', models.CharField(default='Con cosa lavoro', max_length=200, verbose_name='Заголовок (IT)')),
                ('intro_uk', models.TextField(blank=True, default='', verbose_name='Вступ (UA)')),
                ('intro_it', models.TextField(blank=True, default='', verbose_name='Вступ (IT)')),
            ],
            options={
                'verbose_name': 'З чим я працюю',
                'verbose_name_plural': 'З чим я працюю',
            },
        ),
        migrations.CreateModel(
            name='TherapyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uk', models.CharField(default='Як проходить терапія', max_length=200, verbose_name='Заголовок (UA)')),
                ('title_it', models.CharField(default='Come si svolge la terapia', max_length=200, verbose_name='Заголовок (IT)')),
                ('intro_uk', models.TextField(blank=True, default='', verbose_name='Вступ (UA)')),
                ('intro_it', models.TextField(blank=True, default='', verbose_name='Вступ (IT)')),
                ('format_online_uk', models.TextField(blank=True, default='', verbose_name='Формат онлайн (UA)')),
                ('format_online_it', models.TextField(blank=True, default='', verbose_name='Формат онлайн (IT)')),
                ('format_offline_uk', models.TextField(blank=True, default='', verbose_name='Формат офлайн (UA)')),
                ('format_offline_it', models.TextField(blank=True, default='', verbose_name='Формат офлайн (IT)')),
                ('pricing_note_uk', models.TextField(blank=True, default='', verbose_name='Тривалість і вартість (UA)')),
                ('pricing_note_it', models.TextField(blank=True, default='', verbose_name='Тривалість і вартість (IT)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='therapy/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Як проходить терапія',
                'verbose_name_plural': 'Як проходить терапія',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('title_uk', models.CharField(max_length=160, verbose_name='Назва (UA)')),
                ('title_it', models.CharField(blank=True, default='', max_length=160, verbose_name='Назва (IT)')),
                ('description_uk', models.TextField(blank=True, default='', verbose_name='Опис (UA)')),
                ('description_it', models.TextField(blank=True, default='', verbose_name='Опис (IT)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.servicespage')),
            ],
            options={
                'verbose_name': 'Тема роботи',
                'verbose_name_plural': 'Теми роботи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TherapyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Крок')),
                ('title_uk', models.CharField(max_length=160, verbose_name='Назва (UA)')),
                ('title_it', models.CharField(blank=True, default='', max_length=160, verbose_name='Назва (IT)')),
                ('body_uk', models.TextField(blank=True, default='', verbose_name='Опис (UA)')),
                ('body_it', models.TextField(blank=True, default='', verbose_name='Опис (IT)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pages.therapypage')),
            ],
            options={
                'verbose_name': 'Крок терапії',
                'verbose_name_plural': 'Кроки терапії',
                'ordering': ['order', 'id'],
            },
        ),
    ]
