# Generated by Django 5.1.15 on 2026-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_update_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'З якими запитами працюю', 'verbose_name_plural': 'З якими запитами працюю'},
        ),
        migrations.AlterModelOptions(
            name='therapypage',
            options={'verbose_name': 'Як проходять зустрічі', 'verbose_name_plural': 'Як проходять зустрічі'},
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='title_uk',
            field=models.CharField(default='З якими запитами працюю', max_length=200, verbose_name='Заголовок (UA)'),
        ),
        migrations.AlterField(
            model_name='therapypage',
            name='title_uk',
            field=models.CharField(default='Як проходять зустрічі', max_length=200, verbose_name='Заголовок (UA)'),
        ),
    ]
