# Generated by Django 5.1.15 on 2026-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_content_polish_and_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespage',
            options={'verbose_name': 'З чим я працюю', 'verbose_name_plural': 'З чим я працюю'},
        ),
        migrations.AlterModelOptions(
            name='therapystep',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Крок роботи', 'verbose_name_plural': 'Кроки роботи'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='therapy_intro_it',
            field=models.TextField(blank=True, default='', verbose_name='Тизер «Як проходять зустрічі» (IT)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='therapy_intro_uk',
            field=models.TextField(blank=True, default='', verbose_name='Тизер «Як проходять зустрічі» (UA)'),
        ),
    ]
