# Generated by Django 5.1.15 on 2026-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_fix_pricing_note_preposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_teaser_it',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_teaser_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contacts_teaser_it',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contacts_teaser_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_intro_it',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_intro_uk',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='therapy_intro_it',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='therapy_intro_uk',
        ),
    ]
